name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure to match your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Remove cache directory
      run: rm -rf ./.cache  # Optional, to avoid potential cache issues

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Ensure this matches your build output directory
        allow_empty_commit: true  # To avoid empty commit issues
